### ISSUE TITLE
integrate REST API

### ISSUE THREAD

**Issue by CocoaRush** [alvittoag/ChatPGT-Messenger#1]
Hi, Alvitto

I like this project very much! Good work!

Just don't know how to reach you, but I'm wondering if you can make new ChatGPT-Messenger version which can use REST API for the logins, chats etc...

I'm extremely new to the front-end developing, but every interested in building a ChatGPT style website, or you can kindly guild me how to adjust your project to use the REST API, thanks!

**Comment by alvittoag** [comment]
You can use the official API from OpenAI, I also use the API from there and I use firebase to store chat and login history
